/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PurchaseRequestRouteRouteImport } from './routes/purchase-request/route'
import { Route as AssetInventoryRouteRouteImport } from './routes/asset-inventory/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PurchaseRequestIndexRouteImport } from './routes/purchase-request/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AssetInventoryIndexRouteImport } from './routes/asset-inventory/index'
import { Route as PurchaseRequestRequestsIndexRouteImport } from './routes/purchase-request/requests/index'
import { Route as PurchaseRequestDashboardIndexRouteImport } from './routes/purchase-request/dashboard/index'
import { Route as AssetInventoryUsersIndexRouteImport } from './routes/asset-inventory/users/index'
import { Route as AssetInventoryDashboardIndexRouteImport } from './routes/asset-inventory/dashboard/index'
import { Route as AssetInventoryCategoriesIndexRouteImport } from './routes/asset-inventory/categories/index'
import { Route as AssetInventoryAssetsIndexRouteImport } from './routes/asset-inventory/assets/index'
import { Route as AssetInventoryAssetLogsIndexRouteImport } from './routes/asset-inventory/asset-logs/index'
import { Route as AssetInventoryAssetsIdRouteImport } from './routes/asset-inventory/assets/$id'
import { Route as AssetInventoryAssetsPrintIndexRouteImport } from './routes/asset-inventory/assets/print/index'

const PurchaseRequestRouteRoute = PurchaseRequestRouteRouteImport.update({
  id: '/purchase-request',
  path: '/purchase-request',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetInventoryRouteRoute = AssetInventoryRouteRouteImport.update({
  id: '/asset-inventory',
  path: '/asset-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRequestIndexRoute = PurchaseRequestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PurchaseRequestRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetInventoryIndexRoute = AssetInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssetInventoryRouteRoute,
} as any)
const PurchaseRequestRequestsIndexRoute =
  PurchaseRequestRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => PurchaseRequestRouteRoute,
  } as any)
const PurchaseRequestDashboardIndexRoute =
  PurchaseRequestDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => PurchaseRequestRouteRoute,
  } as any)
const AssetInventoryUsersIndexRoute =
  AssetInventoryUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AssetInventoryRouteRoute,
  } as any)
const AssetInventoryDashboardIndexRoute =
  AssetInventoryDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AssetInventoryRouteRoute,
  } as any)
const AssetInventoryCategoriesIndexRoute =
  AssetInventoryCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AssetInventoryRouteRoute,
  } as any)
const AssetInventoryAssetsIndexRoute =
  AssetInventoryAssetsIndexRouteImport.update({
    id: '/assets/',
    path: '/assets/',
    getParentRoute: () => AssetInventoryRouteRoute,
  } as any)
const AssetInventoryAssetLogsIndexRoute =
  AssetInventoryAssetLogsIndexRouteImport.update({
    id: '/asset-logs/',
    path: '/asset-logs/',
    getParentRoute: () => AssetInventoryRouteRoute,
  } as any)
const AssetInventoryAssetsIdRoute = AssetInventoryAssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => AssetInventoryRouteRoute,
} as any)
const AssetInventoryAssetsPrintIndexRoute =
  AssetInventoryAssetsPrintIndexRouteImport.update({
    id: '/assets/print/',
    path: '/assets/print/',
    getParentRoute: () => AssetInventoryRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asset-inventory': typeof AssetInventoryRouteRouteWithChildren
  '/purchase-request': typeof PurchaseRequestRouteRouteWithChildren
  '/asset-inventory/': typeof AssetInventoryIndexRoute
  '/login': typeof LoginIndexRoute
  '/purchase-request/': typeof PurchaseRequestIndexRoute
  '/asset-inventory/assets/$id': typeof AssetInventoryAssetsIdRoute
  '/asset-inventory/asset-logs': typeof AssetInventoryAssetLogsIndexRoute
  '/asset-inventory/assets': typeof AssetInventoryAssetsIndexRoute
  '/asset-inventory/categories': typeof AssetInventoryCategoriesIndexRoute
  '/asset-inventory/dashboard': typeof AssetInventoryDashboardIndexRoute
  '/asset-inventory/users': typeof AssetInventoryUsersIndexRoute
  '/purchase-request/dashboard': typeof PurchaseRequestDashboardIndexRoute
  '/purchase-request/requests': typeof PurchaseRequestRequestsIndexRoute
  '/asset-inventory/assets/print': typeof AssetInventoryAssetsPrintIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asset-inventory': typeof AssetInventoryIndexRoute
  '/login': typeof LoginIndexRoute
  '/purchase-request': typeof PurchaseRequestIndexRoute
  '/asset-inventory/assets/$id': typeof AssetInventoryAssetsIdRoute
  '/asset-inventory/asset-logs': typeof AssetInventoryAssetLogsIndexRoute
  '/asset-inventory/assets': typeof AssetInventoryAssetsIndexRoute
  '/asset-inventory/categories': typeof AssetInventoryCategoriesIndexRoute
  '/asset-inventory/dashboard': typeof AssetInventoryDashboardIndexRoute
  '/asset-inventory/users': typeof AssetInventoryUsersIndexRoute
  '/purchase-request/dashboard': typeof PurchaseRequestDashboardIndexRoute
  '/purchase-request/requests': typeof PurchaseRequestRequestsIndexRoute
  '/asset-inventory/assets/print': typeof AssetInventoryAssetsPrintIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asset-inventory': typeof AssetInventoryRouteRouteWithChildren
  '/purchase-request': typeof PurchaseRequestRouteRouteWithChildren
  '/asset-inventory/': typeof AssetInventoryIndexRoute
  '/login/': typeof LoginIndexRoute
  '/purchase-request/': typeof PurchaseRequestIndexRoute
  '/asset-inventory/assets/$id': typeof AssetInventoryAssetsIdRoute
  '/asset-inventory/asset-logs/': typeof AssetInventoryAssetLogsIndexRoute
  '/asset-inventory/assets/': typeof AssetInventoryAssetsIndexRoute
  '/asset-inventory/categories/': typeof AssetInventoryCategoriesIndexRoute
  '/asset-inventory/dashboard/': typeof AssetInventoryDashboardIndexRoute
  '/asset-inventory/users/': typeof AssetInventoryUsersIndexRoute
  '/purchase-request/dashboard/': typeof PurchaseRequestDashboardIndexRoute
  '/purchase-request/requests/': typeof PurchaseRequestRequestsIndexRoute
  '/asset-inventory/assets/print/': typeof AssetInventoryAssetsPrintIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asset-inventory'
    | '/purchase-request'
    | '/asset-inventory/'
    | '/login'
    | '/purchase-request/'
    | '/asset-inventory/assets/$id'
    | '/asset-inventory/asset-logs'
    | '/asset-inventory/assets'
    | '/asset-inventory/categories'
    | '/asset-inventory/dashboard'
    | '/asset-inventory/users'
    | '/purchase-request/dashboard'
    | '/purchase-request/requests'
    | '/asset-inventory/assets/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asset-inventory'
    | '/login'
    | '/purchase-request'
    | '/asset-inventory/assets/$id'
    | '/asset-inventory/asset-logs'
    | '/asset-inventory/assets'
    | '/asset-inventory/categories'
    | '/asset-inventory/dashboard'
    | '/asset-inventory/users'
    | '/purchase-request/dashboard'
    | '/purchase-request/requests'
    | '/asset-inventory/assets/print'
  id:
    | '__root__'
    | '/'
    | '/asset-inventory'
    | '/purchase-request'
    | '/asset-inventory/'
    | '/login/'
    | '/purchase-request/'
    | '/asset-inventory/assets/$id'
    | '/asset-inventory/asset-logs/'
    | '/asset-inventory/assets/'
    | '/asset-inventory/categories/'
    | '/asset-inventory/dashboard/'
    | '/asset-inventory/users/'
    | '/purchase-request/dashboard/'
    | '/purchase-request/requests/'
    | '/asset-inventory/assets/print/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetInventoryRouteRoute: typeof AssetInventoryRouteRouteWithChildren
  PurchaseRequestRouteRoute: typeof PurchaseRequestRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/purchase-request': {
      id: '/purchase-request'
      path: '/purchase-request'
      fullPath: '/purchase-request'
      preLoaderRoute: typeof PurchaseRequestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-inventory': {
      id: '/asset-inventory'
      path: '/asset-inventory'
      fullPath: '/asset-inventory'
      preLoaderRoute: typeof AssetInventoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-request/': {
      id: '/purchase-request/'
      path: '/'
      fullPath: '/purchase-request/'
      preLoaderRoute: typeof PurchaseRequestIndexRouteImport
      parentRoute: typeof PurchaseRequestRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset-inventory/': {
      id: '/asset-inventory/'
      path: '/'
      fullPath: '/asset-inventory/'
      preLoaderRoute: typeof AssetInventoryIndexRouteImport
      parentRoute: typeof AssetInventoryRouteRoute
    }
    '/purchase-request/requests/': {
      id: '/purchase-request/requests/'
      path: '/requests'
      fullPath: '/purchase-request/requests'
      preLoaderRoute: typeof PurchaseRequestRequestsIndexRouteImport
      parentRoute: typeof PurchaseRequestRouteRoute
    }
    '/purchase-request/dashboard/': {
      id: '/purchase-request/dashboard/'
      path: '/dashboard'
      fullPath: '/purchase-request/dashboard'
      preLoaderRoute: typeof PurchaseRequestDashboardIndexRouteImport
      parentRoute: typeof PurchaseRequestRouteRoute
    }
    '/asset-inventory/users/': {
      id: '/asset-inventory/users/'
      path: '/users'
      fullPath: '/asset-inventory/users'
      preLoaderRoute: typeof AssetInventoryUsersIndexRouteImport
      parentRoute: typeof AssetInventoryRouteRoute
    }
    '/asset-inventory/dashboard/': {
      id: '/asset-inventory/dashboard/'
      path: '/dashboard'
      fullPath: '/asset-inventory/dashboard'
      preLoaderRoute: typeof AssetInventoryDashboardIndexRouteImport
      parentRoute: typeof AssetInventoryRouteRoute
    }
    '/asset-inventory/categories/': {
      id: '/asset-inventory/categories/'
      path: '/categories'
      fullPath: '/asset-inventory/categories'
      preLoaderRoute: typeof AssetInventoryCategoriesIndexRouteImport
      parentRoute: typeof AssetInventoryRouteRoute
    }
    '/asset-inventory/assets/': {
      id: '/asset-inventory/assets/'
      path: '/assets'
      fullPath: '/asset-inventory/assets'
      preLoaderRoute: typeof AssetInventoryAssetsIndexRouteImport
      parentRoute: typeof AssetInventoryRouteRoute
    }
    '/asset-inventory/asset-logs/': {
      id: '/asset-inventory/asset-logs/'
      path: '/asset-logs'
      fullPath: '/asset-inventory/asset-logs'
      preLoaderRoute: typeof AssetInventoryAssetLogsIndexRouteImport
      parentRoute: typeof AssetInventoryRouteRoute
    }
    '/asset-inventory/assets/$id': {
      id: '/asset-inventory/assets/$id'
      path: '/assets/$id'
      fullPath: '/asset-inventory/assets/$id'
      preLoaderRoute: typeof AssetInventoryAssetsIdRouteImport
      parentRoute: typeof AssetInventoryRouteRoute
    }
    '/asset-inventory/assets/print/': {
      id: '/asset-inventory/assets/print/'
      path: '/assets/print'
      fullPath: '/asset-inventory/assets/print'
      preLoaderRoute: typeof AssetInventoryAssetsPrintIndexRouteImport
      parentRoute: typeof AssetInventoryRouteRoute
    }
  }
}

interface AssetInventoryRouteRouteChildren {
  AssetInventoryIndexRoute: typeof AssetInventoryIndexRoute
  AssetInventoryAssetsIdRoute: typeof AssetInventoryAssetsIdRoute
  AssetInventoryAssetLogsIndexRoute: typeof AssetInventoryAssetLogsIndexRoute
  AssetInventoryAssetsIndexRoute: typeof AssetInventoryAssetsIndexRoute
  AssetInventoryCategoriesIndexRoute: typeof AssetInventoryCategoriesIndexRoute
  AssetInventoryDashboardIndexRoute: typeof AssetInventoryDashboardIndexRoute
  AssetInventoryUsersIndexRoute: typeof AssetInventoryUsersIndexRoute
  AssetInventoryAssetsPrintIndexRoute: typeof AssetInventoryAssetsPrintIndexRoute
}

const AssetInventoryRouteRouteChildren: AssetInventoryRouteRouteChildren = {
  AssetInventoryIndexRoute: AssetInventoryIndexRoute,
  AssetInventoryAssetsIdRoute: AssetInventoryAssetsIdRoute,
  AssetInventoryAssetLogsIndexRoute: AssetInventoryAssetLogsIndexRoute,
  AssetInventoryAssetsIndexRoute: AssetInventoryAssetsIndexRoute,
  AssetInventoryCategoriesIndexRoute: AssetInventoryCategoriesIndexRoute,
  AssetInventoryDashboardIndexRoute: AssetInventoryDashboardIndexRoute,
  AssetInventoryUsersIndexRoute: AssetInventoryUsersIndexRoute,
  AssetInventoryAssetsPrintIndexRoute: AssetInventoryAssetsPrintIndexRoute,
}

const AssetInventoryRouteRouteWithChildren =
  AssetInventoryRouteRoute._addFileChildren(AssetInventoryRouteRouteChildren)

interface PurchaseRequestRouteRouteChildren {
  PurchaseRequestIndexRoute: typeof PurchaseRequestIndexRoute
  PurchaseRequestDashboardIndexRoute: typeof PurchaseRequestDashboardIndexRoute
  PurchaseRequestRequestsIndexRoute: typeof PurchaseRequestRequestsIndexRoute
}

const PurchaseRequestRouteRouteChildren: PurchaseRequestRouteRouteChildren = {
  PurchaseRequestIndexRoute: PurchaseRequestIndexRoute,
  PurchaseRequestDashboardIndexRoute: PurchaseRequestDashboardIndexRoute,
  PurchaseRequestRequestsIndexRoute: PurchaseRequestRequestsIndexRoute,
}

const PurchaseRequestRouteRouteWithChildren =
  PurchaseRequestRouteRoute._addFileChildren(PurchaseRequestRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetInventoryRouteRoute: AssetInventoryRouteRouteWithChildren,
  PurchaseRequestRouteRoute: PurchaseRequestRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
